import type { Metadata } from "next";
import localFont from "next/font/local";
import TranslationsProvider from "@/utils/TranslationsProvider";
import { LenisProvider } from "@/components";
import initTranslations from "../i18n";
import "../../styles/globals.scss";

const regular = localFont({
  src: "../fonts/Inter-Regular.ttf",
  variable: "--regular-font",
});

const medium = localFont({
  src: "../fonts/Inter-Medium.ttf",
  variable: "--medium-font",
});

const semibold = localFont({
  src: "../fonts/Inter-Semibold.ttf",
  variable: "--semibold-font",
});


export const metadata: Metadata = {
  title: "CUE - Communauté Urbaine d'Ebolowa",
  description: "Generated by create next app",
};

/**Translations */
const i18nNamespaces = ["Navigation", "HomePage"];

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // ① Await the promise:
  const { locale } = await params;

  const { resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <html lang={locale}>
      <body
        className={`${regular.variable} ${medium.variable} ${semibold.variable}`}
      >
        <
        <TranslationsProvider
          resources={resources}
          locale={locale}
          namespaces={i18nNamespaces}
        >
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
