import type { Metadata } from "next";
import localFont from "next/font/local";
import TranslationsProvider from "@/utils/TranslationsProvider";
import initTranslations from "../i18n";
import "../../styles/globals.scss"

const book = localFont({
  src: "../fonts/SequelSans-Book.ttf",
  variable: "--book-font",
});

const roman = localFont({
  src: "../fonts/SequelSans-Roman.ttf",
  variable: "--roman-font",
});

const medium = localFont({
  src: "../fonts/SequelSans-Medium.ttf",
  variable: "--medium-font",
});

const bold = localFont({
  src: "../fonts/SequelSans-Bold.ttf",
  variable: "--bold-font",
});


export const metadata: Metadata = {
  title: "CUE - Communauté Urbaine d'Ebolowa",
  description: "Generated by create next app",
};

/**Translations */
const i18nNamespaces = [
  "Navigation",
  "HomePage",
];

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // ① Await the promise:
  const { locale } = await params;

  const { resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <html lang="en">
      <body className={`${book.variable} ${roman.variable} ${medium.variable} ${bold.variable}`}>
        {children}
      </body>
    </html>
  );
}
