import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../styles/globals.scss"

const book = localFont({
  src: "../fonts/SequelSans-Book.ttf",
  variable: "--book-font",
});

const roman = localFont({
  src: "../fonts/SequelSans-Roman.ttf",
  variable: "--roman-font",
});

const medium = localFont({
  src: "../fonts/SequelSans-Medium.ttf",
  variable: "--medium-font",
});

const bold = localFont({
  src: "../fonts/SequelSans-Bold.ttf",
  variable: "--bold-font",
});


export const metadata: Metadata = {
  title: "CUE - Communauté Urbaine d'Ebolowa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
